home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

issues/api/urls.py
from django.urls import path
from django.conf.urls import include
from rest_framework_nested import routers
from . import views


router = routers.DefaultRouter()
router.register(r"attachments", views.AttachmentViewSet, basename="attachment")
router.register(r"", views.ProjectAPIViewset, basename="projects")

## generates:
# /projects/
# /projects/{pk}/
# (projects/ is already defined in global urls)

projects_router = routers.NestedDefaultRouter(router, r"", lookup="projects")
projects_router.register(r"issues", views.IssueAPIViewset, basename="issues")
projects_router.register(r"labels", views.LabelAPIViewset, basename="labels")

## generates:
# /projects/
# /projects/{project_slug}/issues/
# /projects/{project_slug}/issues/{pk}/

issues_router = routers.NestedDefaultRouter(projects_router, r"issues", lookup="issues")
issues_router.register(r"comments", views.CommentAPIViewset, basename="comments")
issues_router.register(r"labels", views.IssueLabelAPIViewset, basename="issue-labels")
## generates:
# /projects/
# /projects/{project_slug}/issues/
# /projects/{project_slug}/issues/{pk}/
# /projects/{project_slug}/issues/{issues_issue_id}/comments/
# /projects/{project_slug}/issues/{issues_issue_id}//comments/{pk}/
# /projects/{project_slug}/issues/{issues_issue_id}/labels/
# /projects/{project_slug}/issues/{issues_issue_id}//labels/{pk}/

urlpatterns = [
    path(r"", include(router.urls)),
    path(r"", include(projects_router.urls)),
    path(r"", include(issues_router.urls)),
]

issues/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.ProjectsListView.as_view(), name='projects-list'),
    path('new/', views.ProjectsCreateView.as_view(), name='project-create'),
    path('<slug:slug>/members/', views.ProjectAddMemberView.as_view(), name='project-add-member'),
    path('<slug:slug>/', views.ProjectDetailView.as_view(), name='project-detail'),
    path('<slug:slug>/issues/', views.IssuesListView.as_view(), name='issues'),
    path('<slug:slug>/issues/new/', views.IssueCreateView.as_view(), name='issue-create'),
    path('<slug:slug>/issues/<issue_id>/', views.IssueDetailView.as_view(), name='issue-detail'),
    path('<slug:slug>/issues/<issue_id>/add-comment/', views.CommentCreateView.as_view(), name='comment-create'),
    path('<slug:slug>/issues/<issue_id>/add-label/', views.LabelCreateView.as_view(), name='label-create'),
    path('<slug:slug>/issues/<issue_id>/add-assignee/', views.AssigneeUpdateView.as_view(), name='assignee-update'),
    path('<slug:slug>/issues/<issue_id>/add-type/', views.TypeUpdateView.as_view(), name='type-update'),
    path('<slug:slug>/issues/<issue_id>/add-status/', views.StatusUpdateView.as_view(), name='status-update'),
    path('<slug:slug>/issues/<issue_id>/add-severity/', views.SeverityUpdateView.as_view(), name='severity-update'),
    path('<slug:slug>/issues/<issue_id>/add-deadline/', views.DeadlineUpdateView.as_view(), name='deadline-update'),
    path('<slug:slug>/issues/<issue_id>/add-resolution/', views.ResolutionUpdateView.as_view(), name='resolution-update'),
    path('<slug:slug>/issues/<issue_id>/add-references/', views.ReferencesUpdateView.as_view(), name='references-update'),
    path('<slug:slug>/issues/<issue_id>/add-priority/', views.PriorityUpdateView.as_view(), name='priority-update'),
]

openfix/urls.py
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include

from rest_framework.authtoken.views import obtain_auth_token

from .views import APIRootView

api = [
    path('', APIRootView.as_view()),
    path('users/', include('users.api.urls')),
    path('projects/', include('issues.api.urls')),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(api)),
    path('api-auth/', include("rest_framework.urls")),
    path('api-token-auth/', obtain_auth_token),
    
    path('', include('home.urls')),
    path('projects/', include('issues.urls')),

    path('', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

issues/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.template.defaultfilters import slugify
from django.db.models.signals import m2m_changed
from django.dispatch import receiver

from .utils import int_choices, char_choices, is_dark
from .validators import validate_color

User = get_user_model()

class Attachment(models.Model):

    attachment = models.FileField(upload_to='attachments')


class Project(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(null=False, unique=True, blank=True)
    short_description = models.CharField(max_length=250, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    visible = models.BooleanField(default=False)
    members = models.ManyToManyField(
        User, related_name='projects', blank=True
    )
    maintainers = models.ManyToManyField(
        User, related_name='maintainer_in', blank=True
    )

    def __str__(self):
        return "%s - %s" % (self.pk, self.name)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

@receiver(m2m_changed, sender=Project.maintainers.through)
def user_maintainer(sender, instance, **kwargs):
    members =  instance.members.all()
    for maintainer in instance.maintainers.all():
        if maintainer not in members:
            instance.members.add(maintainer)



class Issue(models.Model):

    TYPE_CHOICES = char_choices(
        'bug', 'enhancement', 'task', 'question'
    )

    STATUS_CHOICES = char_choices(
        'new', 'assigned', 'resolved', 'reopened',
        'verified', 'invalid', 'cancelled'
    )

    RESOLUTION_CHOICES = char_choices(
        'fixed', 'invalid', 'wontfix', 'inactive', 
        'duplicate', 'worksforme', 'incomplete', 
        'support', 'expired', 'moved'
    )

    SEVERITY_CHOICES = char_choices(
        'low', 'normal', 'severe'
    )

    title = models.CharField(max_length=200)
    issue_id = models.IntegerField(blank=True) # id that increments per project not db
    issue_type = models.CharField(max_length=12, choices=TYPE_CHOICES, default='BUG')
    description = models.TextField(null=True, blank=True)
    assignee = models.ForeignKey(User, related_name="assigned_issues", on_delete=models.DO_NOTHING, null=True, blank=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='NEW')
    is_open = models.BooleanField(default=True)
    resolution = models.CharField(max_length=11, choices=RESOLUTION_CHOICES, null=True, blank=True)
    priority = models.IntegerField(choices=int_choices(11, 1), null=True, blank=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='issues')
    severity = models.CharField(max_length=11, choices=SEVERITY_CHOICES, null=True, blank=True)
    references = models.ManyToManyField('self', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, related_name="issues", on_delete=models.DO_NOTHING)
    updated_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True, blank=True)
    deadline = models.DateTimeField(null=True, blank=True)

    def save(self, *args, **kwargs):
        # makes sure issue_id is always autogenerated. Kinda meh but it works.
        if not self.pk:
            self.issue_id = self.__class__.objects.filter(project=self.project).count() + 1
        else:
            self.issue_id = self.__class__.objects.get(id=self.pk).issue_id
        return super().save(*args, **kwargs)

    def __str__(self):
        return "%s - %s" % (self.id, self.title)

    class Meta:
        unique_together = ['id', 'issue_id']
        ordering = ('-issue_id', '-id')


class Label(models.Model):
    name = models.CharField(max_length=20)
    background_color = models.CharField(max_length=7, validators=[validate_color])
    issues = models.ManyToManyField(Issue, related_name='labels', blank=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='labels')
    color = models.CharField(max_length=7, null=True, blank=True)

    def save(self, *args, **kwargs):
        if is_dark(self.background_color):
            self.color = '#fff'
        else:
            self.color = '#000'
        return super().save(*args, **kwargs)

    def __str__(self):
        return "%s - %s" % (self.name, self.background_color)


class Comment(models.Model):
    issue = models.ForeignKey(
        Issue, related_name='comments', on_delete=models.CASCADE
    )
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    edited = models.BooleanField(default=False)
    reply_to = models.OneToOneField(to="Comment", on_delete=models.DO_NOTHING, blank=True, null=True)
    extra = models.JSONField(blank=True, null=True)

    def __str__(self):
        return "'%s' by '%s'" % (self.id, self.owner)

    # def clean(self):
    #     validate_reply(self)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        # TODO notifications

    
    class Meta:
        ordering = ('timestamp', 'id')

issues/api/views.py
from django.db.models import Q
from django.shortcuts import get_object_or_404
from rest_framework import status, viewsets
from rest_framework.response import Response
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticated, IsAdminUser

from ..models import Project, Issue, Comment, Label, Attachment
from ..permissions import IsCommentOwnerOrReadOnly, IsIssueOwnerOrReadOnly, IsProjectMember, is_user_admin
from .serializers import (
    ProjectSerializer, IssueSerializer, 
    CommentSerializer, LabelSerializer, AttachmentSerializer
)

class AttachmentViewSet(viewsets.ModelViewSet):

    permission_classes = [IsAdminUser]
    queryset = Attachment.objects.all()
    serializer_class = AttachmentSerializer

    @action(detail=False, methods=['post'], permission_classes=[IsAuthenticated])
    def add(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)


class ProjectAPIViewset(viewsets.ModelViewSet):

    permission_classes = [IsProjectMember|IsAdminUser]
    queryset = Project.objects.all()
    serializer_class = ProjectSerializer
    search_fields = ['name']
    lookup_field = 'slug'
    lookup_url_kwarg = 'slug'

    @action(detail=True, methods=['post'], url_path='append-label')
    def append_label(self, request, *args, **kwargs):
        proj = get_object_or_404(Project, slug=kwargs["slug"])
        issue = proj.issues.get(issue_id=request.data.get('issue_id'))
        label = proj.labels.get(id=request.data.get('label_id'))
        label.issues.add(issue)
        return Response(
            LabelSerializer(issue.labels, many=True).data
        )

    def dispatch(self, request, *args, **kwargs):
        if not is_user_admin(request):
            self.queryset = Project.objects.filter(Q(members=request.user) | Q(visible=True))
        return super().dispatch(request, *args, **kwargs)

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        instance = serializer.save()
        if request.user not in instance.maintainers.all():
            instance.maintainers.add(request.user)
        headers = self.get_success_headers(serializer.data)
        return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)


class IssueAPIViewset(viewsets.ModelViewSet):

    permission_classes = [IsIssueOwnerOrReadOnly|IsAdminUser]
    queryset = Issue.objects.all()
    serializer_class = IssueSerializer
    search_fields = ['title']
    lookup_field = 'issue_id'
    lookup_url_kwarg = 'issue_id'

    def get_queryset(self):
        return Issue.objects.filter(project__slug=self.kwargs['projects_slug'])

class CommentAPIViewset(viewsets.ModelViewSet):

    permission_classes = [IsCommentOwnerOrReadOnly|IsAdminUser]
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    search_fields = ['content']

    def get_queryset(self):
        return Comment.objects.filter(
            issue__project__slug=self.kwargs['projects_slug'],
            issue__issue_id=self.kwargs['issues_issue_id']
        )


class LabelAPIViewset(viewsets.ModelViewSet):

    permission_classes = [IsAuthenticated]
    queryset = Label.objects.all()
    serializer_class = LabelSerializer
    search_fields = ['name']

    def get_queryset(self):
        return Label.objects.filter(
            project__slug=self.kwargs['projects_slug']
        )

class IssueLabelAPIViewset(LabelAPIViewset):

    def get_queryset(self):
        return Label.objects.filter(
            project__slug=self.kwargs['projects_slug'],
            issues__issue_id=self.kwargs['issues_issue_id']
        )

issues/templates/issues/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Projects - OpenFix{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'issues/css/issues_index.css' %}" />
{% endblock extra_css %}

{% block content %}

<div class="container">

    <div class="page-title-holder d-flex align-items-center">
        <h1 class="page-title">Projects</h1>
        <div class="page-title-controls">
        <a class="btn btn-success" data-qa-selector="new_project_button" href="/projects/new">New project</a>
        </div>
    </div>

    <!-- Projects list -->
    <ul class="list-group list-group-flush issues-list">
        {% for project in page_obj %}
            <li class="list-group-item p-4">
                <div class="title">
                    <a href="{{ project.slug }}" class="no-decoration">{{ project.name }}</a>
                    {% if user in project.maintainers.all %}
                    <span class="badge rounded-pill bg-secondary" style="margin-left: 10px;">Maintainer</span>
                    {% endif %}
                </div>
                {% if project.short_description %}
                    <div class="project-short-description">
                        {{ project.short_description|truncatechars:95 }}
                    </div>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
    {% if  page_obj.paginator.num_pages > 1 %}
    <!-- Pagination -->
    <nav class="issues-pagination" aria-label="issues-pagination">
        <ul class="pagination">
            <!-- Previous -->
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link">Previous</a>
                </li>
            {% endif %}
            <!-- pages - need better renderer for many pages -->
            {% for page_number in page_obj.paginator.page_range %}
                
                {% if page_number < 15 or page_number ==  page_obj.paginator.num_pages %}
                <li class="page-item {% if page_obj.number == page_number %}active{% endif %}">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
                {% endif %}
            
            {% endfor %}

            <!-- Next -->
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link">Next</a>
                </li>
            {% endif %}
            
        </ul>
      </nav>
      {% endif %}
</div>
{% endblock content %}

issues/templates/issues/issue_new.html
{% extends 'base.html' %}
{% load static %}

{% block title %}New issue{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'openfix/highlight/css/onedark.css' %}" />
<link rel="stylesheet" href="{% static 'issues/css/issues_index.css' %}" />
{% endblock extra_css %}

{% block content %}

<div class="container">

    <!-- Breadcrumps -->
    <div class="d-flex align-items-center mt-3">
        <div class="bread-crubs">
            <a href="/" class="no-decoration">Home</a> >
            <a href="../../../" class="no-decoration">Projects</a> >
            <a href="../../" class="no-decoration">{{ project_name }}</a> >
            <a href="../" class="no-decoration">Issues</a> >
            <a href="." class="no-decoration">New issue </a>
        </div>
    </div>

    <div class="page-title-holder d-flex align-items-center">
        <h1 class="page-title">New Issue</h1>
    </div>

    <form method="post">
        <div class="form-group">
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleFormControlInput1" class="mt-2">Issue title</label>
                <input type="text" class="form-control mb-3 mt-2" id="id_name" placeholder="Issue name" name="title" maxlength="200" required>
            </div>
            <label for="new-issue-text-area" class="mb-2 mt-4">Issue description</label>
            <ul class="nav nav-tabs" id="comment-tab" role="tablist">
                <li class="nav-item" role="presentation">
                    <button class="nav-link active" id="write-tab" data-bs-toggle="tab" data-bs-target="#write" type="button" role="tab" aria-controls="write" aria-selected="true">
                        Write
                    </button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="preview-tab" data-bs-toggle="tab" data-bs-target="#preview" type="button" role="tab" aria-controls="preview" aria-selected="false">
                        Preview
                    </button>
                </li>
            </ul>
            <div class="tab-content" id="comment-tab-content">
                <div class="tab-pane fade show active" id="write" role="tabpanel" aria-labelledby="write-tab">
                    <textarea class="form-control mb-3 mt-2 write-textarea" id="new-issue-text-area" rows="3" name="description"></textarea>
                </div>
                <div class="tab-pane fade" id="preview" role="tabpanel" aria-labelledby="preview-tab">
                    <div class="write-comment-content p-3" id="write-comment-content">
                        No preview yet
                    </div>
                </div>
                <input class="btn btn-success" type="submit" value="Submit issue">
            </div>
        </div>
    </form>
    
</div>
{% endblock content %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'openfix/js/purify.min.js' %}"></script>
<script type="text/javascript" src="{% static 'openfix/highlight/js/highlight.min.js' %}"></script>
<script type="text/javascript" src="{% static 'openfix/js/markdown-it.min.js' %}"></script>
<script type="text/javascript" src="{% static 'issues/js/issues_index.js' %}"></script>
{% endblock extra_js %}

issues/templates/issues/issues_error.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Projects - OpenFix{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'issues/css/issues_index.css' %}" />
{% endblock extra_css %}

{% block content %}

<div class="container">
    ERROR!
    <div class="errors-wrapper mb-3">
    {{ form.non_field_errors }}
    </div>
    <div class="errors-wrapper mb-3">
        {{ form.non_field_errors }}
      </div>
      {% for field in form %}
        <div class="fieldWrapper mb-3">
            {{ field.errors }}
            <div class="form-label">{{ field.label_tag }}</div>
            <div class="form-control-wrapper">{{ field }}</div>
            {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
    {% endfor %}
</div>
{% endblock content %}

issues/templates/issues/issues_list.html
{% extends 'base.html' %}
{% load static %}
{% load paginator_tags %}

{% block title %}Issues - OpenFix{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'issues/css/issues_index.css' %}" />
{% endblock extra_css %}

{% block content %}

<div class="container">

    <div class="d-flex align-items-center mt-3">
        <div class="bread-crubs">
            <a href="/" class="no-decoration">Home</a> >
            <a href="../../" class="no-decoration">Projects</a> >
            <a href="../" class="no-decoration">{{ project_name }}</a> >
            <a href="." class="no-decoration">Issues</a>
        </div>
    </div>

    <div class="page-title-holder d-flex align-items-center">
        <h1 class="page-title">{{ project_name }} - issues</h1>
        <div class="page-title-controls">
        <a class="btn btn-success" data-qa-selector="new_project_button" href="new/">New issue</a>
        </div>
    </div>

    <br>

    <ul class="nav nav-tabs">
        <li class="nav-item">
          <a class="nav-link {% if state == "opened" %}active{% endif %}" aria-current="page" href="?state=opened">({{ open_count }}) Open</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if state == "closed" %}active{% endif %}" href="?state=closed">({{ closed_count }}) Closed</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if state == "all" %}active{% endif %}" href="?state=all">All</a>
        </li>
    </ul>

    <!-- Issues list -->
    <ul class="list-group list-group-flush issues-list">
        {% for issue in page_obj %}
            <li class="list-group-item">
                <div class="title">
                    <a href="{{ issue.issue_id }}" class="no-decoration">{{ issue.title }}</a>
                    <span class="comments-count">
                        {{ issue.comments.count }} <i class="bi bi-chat-left-text"></i>
                    </span>
                </div>
                <div class="author">
                    #{{ issue.issue_id }} Created by {{ issue.created_by }} {{ issue.created|timesince }} ago
                </div>
            </li>
        {% endfor %}
        {% if not page_obj %}
            No issues found!
        {% endif %}
    </ul>
    {% get_proper_elided_page_range paginator page_obj.number as page_range %}
    {% if  page_obj.paginator.num_pages > 1 %}
    <!-- Pagination -->
    <nav class="issues-pagination" aria-label="issues-pagination">
        <ul class="pagination">
            <!-- Previous -->
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link">Previous</a>
                </li>
            {% endif %}
            <!-- pages - need better renderer for many pages -->
            {% for page_number in page_range %}
                
                {% if page_number == paginator.ELLIPSIS %}
                    <li class="page-item disabled">
                        <span class="page-link">{{ paginator.ELLIPSIS }}</span>
                    </li>
                {% else %}
                <li class="page-item {% if page_obj.number == page_number %}active{% endif %}">
                    <a class="page-link" href="?page={{ page_number }}&{{ q_params }}">{{ page_number }}</a>
                </li>
                {% endif %}
            
            {% endfor %}

            <!-- Next -->
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link">Next</a>
                </li>
            {% endif %}
            
        </ul>
      </nav>
      {% endif %}
</div>
{% endblock content %}

issues/templates/issues/project_members.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Add new member{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'issues/css/issues_index.css' %}" />
<link rel="stylesheet" href="{% static 'issues/css/project_members.css' %}" />

{% endblock extra_css %}

{% block content %}

<div class="container">

    <div class="d-flex align-items-center mt-3">
        <div class="bread-crubs">
           <a href="/" class="no-decoration">Home</a> >
           <a href="../../" class="no-decoration">Projects</a> >
           <a href="../" class="no-decoration">{{project_name}} </a> >
           <a href="./" class="no-decoration">Members</a>
        </div>
     </div>

    <div class="page-title-holder d-flex align-items-center">
        <h1 class="page-title">Add new member</h1>
    </div>

    <div class="form-group my-5" id="members-input-wrapper">
        <div class="form-group">
            <input type="text" class="form-control mt-2" id="user_select" maxlength="200", placeholder="Search for users">
            <div class="autocomplete-box" id="autocomplete-box"><ul></ul></div>
        </div>
    </div>

    <hr>
    <div class="list-title mt-5">
        <h4>Project members:</h4>
    </div>
    <ul class="list-group mb-3 mt-2" id="project-members-list">
        <p class="placeholder-glow">
            <span class="placeholder col-12"></span>
        </p>
          
        <p class="placeholder-wave">
            <span class="placeholder col-12"></span>
        </p>
    </ul>

    

</div>

<div class="error-message">
    <div class="btn  btn-danger alert alert-dismissible fade show my-5 text-center" role="alert">
        <span id="error-message-content">Server has encoutner uknown erorr!</span>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
</div>

{% endblock content %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'issues/js/project_members.js' %}"></script>
{% endblock extra_js %}

issues/templates/issues/project_new.html
{% extends 'base.html' %}
{% load static %}

{% block title %}New project{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'issues/css/issues_index.css' %}" />
<link rel="stylesheet" href="{% static 'issues/css/project_members.css' %}" />
{% endblock extra_css %}

{% block content %}

<div class="container">

    <div class="page-title-holder d-flex align-items-center">
        <h1 class="page-title">New Project</h1>
    </div>

    <form method="post">
        <div class="form-group">
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleFormControlInput1" class="mt-4">Project name</label>
                <input type="text" class="form-control mb-3 mt-2" id="id_name" placeholder="Project name" name="name" maxlength="200" required>
            </div>
            <div class="form-group">
                <label for="exampleFormControlTextarea1">Short project description</label>
            <textarea class="form-control mb-3 mt-2" id="exampleFormControlTextarea1" rows="3" name="short_description" maxlength="250"></textarea>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="true" id="flexCheckChecked" name="visible" checked>
                <label class="form-check-label" for="flexCheckChecked">
                  Visable
                </label>
            </div>

            <div class="mt-5 d-flex align-items-center">
                Members
            </div>

            <select class="form-select" style="width: 50%;" multiple hidden aria-label="size 3" id="id_members" name="members" autocomplete="off">
            </select>
        
            <div class="form-group my-1" id="users-input-wrapper">
                <div class="form-group" style="position: relative;">
                    <input type="text" class="form-control mt-2" id="user_select" maxlength="200", placeholder="Search for users" autocomplete="off">
                    <div class="autocomplete-box" id="autocomplete-box"><ul></ul></div>
                </div>
            </div>
        
            <hr>
            <ul class="list-group mb-3 mt-2" id="project-users-list"></ul>

            <label for="exampleFormControlTextarea1" class="mb-2 mt-4">Project description</label>
            <ul class="nav nav-tabs" id="comment-tab" role="tablist">
                <li class="nav-item" role="presentation">
                    <button class="nav-link active" id="write-tab" data-bs-toggle="tab" data-bs-target="#write" type="button" role="tab" aria-controls="write" aria-selected="true">
                        Write
                    </button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="preview-tab" data-bs-toggle="tab" data-bs-target="#preview" type="button" role="tab" aria-controls="preview" aria-selected="false">
                        Preview
                    </button>
                </li>
            </ul>
            <div class="tab-content" id="comment-tab-content">
                <div class="tab-pane fade show active" id="write" role="tabpanel" aria-labelledby="write-tab">
                    <textarea class="form-control mb-3 mt-2 write-textarea" id="exampleFormControlTextarea1" rows="3" name="description"></textarea>
                </div>
                <div class="tab-pane fade" id="preview" role="tabpanel" aria-labelledby="preview-tab">
                    <div class="write-comment-content p-3" id="write-comment-content">
                        No preview yet
                    </div>
                </div>
                <input class="btn btn-success" type="submit" value="Add project">
            </div>
        </div>
    </form>
</div>
{% endblock content %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'openfix/js/purify.min.js' %}"></script>
<script type="text/javascript" src="{% static 'openfix/highlight/js/highlight.min.js' %}"></script>
<script type="text/javascript" src="{% static 'openfix/js/markdown-it.min.js' %}"></script>
<script type="text/javascript" src="{% static 'issues/js/issues_index.js' %}"></script>
<script type="text/javascript" src="{% static 'issues/js/project_new.js' %}"></script>

{% endblock extra_js %}